<a href="https://colab.research.google.com/github/Sonu-kumar-08/YBI-INTERNSHIP/blob/main/Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/tested.csv")

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [ ]:
df.count()

PassengerId    418
Survived       418
Pclass         418
Name           418
Sex            418
Age            332
SibSp          418
Parch          418
Ticket         418
Fare           417
Cabin           91
Embarked       418
dtype: int64

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [ ]:
print(df.columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [ ]:
print(df["Survived"].head(15))

0     0
1     1
2     0
3     0
4     1
5     0
6     1
7     0
8     1
9     0
10    0
11    0
12    1
13    0
14    1
Name: Survived, dtype: int64

In [ ]:
selected_columns=[
    "PassengerId",
    "Survived",
    "Name",
    "Cabin"
]

display(df[selected_columns].head())

   PassengerId  Survived                                          Name Cabin
0          892         0                              Kelly, Mr. James   NaN
1          893         1              Wilkes, Mrs. James (Ellen Needs)   NaN
2          894         0                     Myles, Mr. Thomas Francis   NaN
3          895         0                              Wirz, Mr. Albert   NaN
4          896         1  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   NaN

In [ ]:
display(df.iloc[0])

print("First row, third column: ", df.iloc[0,2])

PassengerId                 892
Survived                      0
Pclass                        3
Name           Kelly, Mr. James
Sex                        male
Age                        34.5
SibSp                         0
Parch                         0
Ticket                   330911
Fare                     7.8292
Cabin                       NaN
Embarked                      Q
Name: 0, dtype: object

First row, third column:  3

In [ ]:
age=df[df["Age"]<25]
print(age)

     PassengerId  Survived  Pclass  \
4            896         1       3
5            897         0       3
8            900         1       3
9            901         0       3
12           904         1       1
..           ...       ...     ...
402         1294         1       1
403         1295         0       1
405         1297         0       2
406         1298         0       2
409         1301         1       3

                                              Name     Sex   Age  SibSp  \
4     Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1
5                       Svensson, Mr. Johan Cervin    male  14.0      0
8        Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0      0
9                          Davies, Mr. John Samuel    male  21.0      2
12   Snyder, Mrs. John Pillsbury (Nelle Stevenson)  female  23.0      1
..                                             ...     ...   ...    ...
402                 Gibson, Miss. Dorothy Winifred  female  22.0      0
403                         Carrau, Mr. Jose Pedro    male  17.0      0
405   Nourney, Mr. Alfred (Baron von Drachstedt")"    male  20.0      0
406                      Ware, Mr. William Jeffery    male  23.0      1
409                      Peacock, Miss. Treasteall  female   3.0      1

     Parch              Ticket     Fare Cabin Embarked
4        1             3101298  12.2875   NaN        S
5        0                7538   9.2250   NaN        S
8        0                2657   7.2292   NaN        C
9        0           A/4 48871  24.1500   NaN        S
12       0               21228  82.2667   B45        S
..     ...                 ...      ...   ...      ...
402      1              112378  59.4000   NaN        C
403      0              113059  47.1000   NaN        S
405      0       SC/PARIS 2166  13.8625   D38        C
406      0               28666  10.5000   NaN        S
409      1  SOTON/O.Q. 3101315  13.7750   NaN        S

[131 rows x 12 columns]

In [ ]:
filtered = df[
    (df["Age"]>20)&
    (df["PassengerId"]>30)
]
display(filtered.head(20))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S
11,903,0,1,"Jones, Mr. Charles Cresson",male,46.0,0,0,694,26.0000,NaN,S
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
13,905,0,2,"Howard, Mr. Benjamin",male,63.0,1,0,24065,26.0000,NaN,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
15,907,1,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,NaN,C
16,908,0,2,"Keane, Mr. Daniel",male,35.0,0,0,233734,12.3500,NaN,Q
17,909,0,3,"Assaf, Mr. Gerios",male,21.0,0,0,2692,7.2250,NaN,C
18,910,1,3,"Ilmakangas, Miss. Ida Livija",female,27.0,1,0,STON/O2. 3101270,7.9250,NaN,S
19,911,1,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.0,0,0,2696,7.2250,NaN,C
20,912,0,1,"Rothschild, Mr. Martin",male,55.0,1,0,PC 17603,59.4000,NaN,C
23,915,0,1,"Williams, Mr. Richard Norris II",male,21.0,0,1,PC 17597,61.3792,NaN,C
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C

In [ ]:
print(df["Age"].value_counts())

Age
21.0    17
24.0    17
22.0    16
30.0    15
18.0    13
        ..
44.0     1
5.0      1
51.0     1
3.0      1
38.5     1
Name: count, Length: 79, dtype: int64

In [ ]:
missing_values=df.isnull().sum()

display(missing_values)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
duplicated_count=df.duplicated().sum()

print("Number of duplicate rows: ", duplicated_count)

Number of duplicate rows:  0

In [ ]:
df_clean=df.drop_duplicates().copy()

print("Before: ", len(df))
print("After: ", len(df_clean))

Before:  418
After:  418